name: Maven, Github Actions and Launchable

on:
  push:
    branches:
    - master

env:
  LAUNCHABLE_TOKEN: v1:mt/demo-test:1fb63d4cbd8648108a8b144f45630b49
  GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    - name: Build and Test
      working-directory: ./
      run: | 
        BUILD_NAME=${GITHUB_RUN_ID:=local-$(date +%s)}
        pip3 install --user launchable~=1.0 > /dev/null
        export PATH=~/.local/bin:$PATH
        launchable verify
        launchable record build --name "$BUILD_NAME" --source .
		mvn surefire-report:report
        launchable subset --target 25% --build "$BUILD_NAME" maven src/test/java/testLaunchable/ > subset.txt
        cat subset.txt
		mvn test -Dsurefire.includeFiles=subset.txt
        function record() {
          launchable record tests --build "$BUILD_NAME" maven target/surefire-reports/
        }
        trap record EXIT
        ./gradlew test $(< subset.txt) 